---
title: "Adam"
author: "Samuel Vinter"
date: "2024-12-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pacman::p_load(tidyverse, dplyr, readr, ggplot2)
```

```{r}
setwd("../csv")
Adam <- read_csv("proccsv/Adam.csv")
Adam_5 <- read_delim("fullcsv/Adam_5.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)
Adam_3 <- read_delim("fullcsv/Adam_3.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)
Adam_1 <- read_delim("fullcsv/Adam_1.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)
```

```{r}
Adam5_utt <- Adam_5 %>%
  filter(Speaker=="CHI") %>%
  nrow()

Adam3_utt <- Adam_3 %>%
  filter(Speaker=="CHI") %>%
  nrow()

Adam1_utt <- Adam_1 %>%
  filter(Speaker=="CHI") %>%
  nrow()
```

```{r}
Adam_5_rep <- Adam %>%
  filter(file=="Adam5")

Adam_3_rep <- Adam %>%
  filter(file=="Adam3")

Adam_1_rep <- Adam %>%
  filter(file=="Adam1")
```

```{r}
sprintf("Total utterances for file Adam 1: %d", nrow(Adam_1))
sprintf("Total utterances for file Adam 3: %d", nrow(Adam_3))
sprintf("Total utterances for file Adam 5: %d", nrow(Adam_5))

sprintf("Total CHI utterances for file Adam 1: %d", Adam1_utt)
sprintf("Total CHI utterances for file Adam 3: %d", Adam3_utt)
sprintf("Total CHI utterances for file Adam 5: %d", Adam5_utt)
```

```{r}
desc <- data.frame(
  file = c("Adam 1", "Adam 3", "Adam 5"),
  "total chi utt vs total n" = c(Adam1_utt/nrow(Adam_1), Adam3_utt/nrow(Adam_3), Adam5_utt/nrow(Adam_5)),
  "n repairs vs n of chi utt" = c(nrow(Adam_1_rep)/Adam1_utt, nrow(Adam_3_rep)/Adam3_utt, nrow(Adam_5_rep)/Adam5_utt),
  "n incomprehensible (xxx)" = c((sum(stringr::str_count(Adam_1$Utterance, "xxx"))), (sum(stringr::str_count(Adam_3$Utterance, "xxx"))), (sum(stringr::str_count(Adam_5$Utterance, "xxx")))),
  "n incompr vs total n of chi" = c((sum(stringr::str_count(Adam_1$Utterance, "xxx")))/Adam1_utt, (sum(stringr::str_count(Adam_3$Utterance, "xxx")))/Adam3_utt, (sum(stringr::str_count(Adam_5$Utterance, "xxx")))/Adam5_utt)
)

desc
```


```{r}
ggplot(Adam_5_rep, aes(x = reorder(reptype, reptype, function(x)-length(x)))) +
  aes(fill = reptype) +
  geom_bar() +
  xlab("Repair type") +
  ggtitle("Repair types by count in session 5 for Adam")

ggplot(Adam_3_rep, aes(x = reorder(reptype, reptype, function(x)-length(x)))) +
  aes(fill = reptype) +
  geom_bar() +
  xlab("Repair type") +
  ggtitle("Repair types by count in session 3 for Adam")

ggplot(Adam_1_rep, aes(x = reorder(reptype, reptype, function(x)-length(x)))) +
  aes(fill = reptype) +
  geom_bar() +
  xlab("Repair type") +
  ggtitle("Repair types by count in session 1 for Adam")
```

```{r}
Adam_summ <- Adam %>%
  group_by(file, reptype) %>%
  summarise(count = n(), .groups = "drop") %>%
  na.omit()

# x is file, y is count, lines is different repair types
ggplot(Adam_summ, aes(x = file, y=count, color=reptype, group=reptype)) +
  geom_line(size = 1) +
  geom_point(size = 2, position=position_jitter(width=0.05,height=0.05)) +
  geom_text(aes(label = count), vjust = -0.5, size = 3) +# Add points to highlight individual counts 
  ggtitle("Repair types over time (total) for Adam")
```

```{r}
total_utterances <- data.frame(
  file = c("Adam1", "Adam3", "Adam5"),
  total = c(Adam1_utt, Adam3_utt, Adam5_utt)  # Total utterances for each file
)

Adam_rel <- Adam_summ %>%
  left_join(total_utterances, by = "file") %>%
  mutate(proportion = count / total)

ggplot(Adam_rel, aes(x = file, y = proportion, color = reptype, group = reptype)) +
  geom_line(size = 1) +
  geom_point(size = 2, position=position_jitter(width=0.005,height=0.005)) +
  geom_text(aes(label = scales::percent(proportion, accuracy = 0.01)), vjust = -0.5, size = 3) +
  ggtitle("Repair types over time (relative to total CHI utterances) for Adam")
```

```{r}
Adam_l <- Adam %>%
    pivot_longer(
      cols = c("pause", "search", "repeat", "cause"),
      names_to = "more",
      values_to = "whatsmore",
      values_drop_na = FALSE
    )
```

```{r}
Adam_more_summ <- Adam_l %>%
  group_by(file, whatsmore) %>%
  summarise(count = n(), .groups = "drop") %>%
  na.omit()

# x is file, y is count, lines is different repair types
ggplot(Adam_more_summ, aes(x = file, y=count, color=whatsmore, group=whatsmore)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  geom_text(aes(label = count), vjust = -0.5, size = 3) +# Add points to highlight individual counts 
  ggtitle("Repair causes, types over time (total) for Adam")
```

```{r}
Adam_more_rel <- Adam_more_summ %>%
  left_join(total_utterances, by = "file") %>%
  mutate(proportion = count / total)

ggplot(Adam_more_rel, aes(x = file, y = proportion, color = whatsmore, group = whatsmore)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  geom_text(aes(label = scales::percent(proportion, accuracy = 0.01)), vjust = -0.5, size = 3) +
  ggtitle("Repair causes, types over time (relative to total CHI utterances) for Adam")
```

```{r}
library(caret)
```

```{r}
Adam$reptype <- as.factor(Adam$reptype)
Adam$cause <- as.factor(Adam$cause)
Adam$search <- as.factor(Adam$search)
Adam$`repeat` <- as.factor(Adam$`repeat`)
Adam$pause <- as.factor(Adam$pause)
```

```{r}
dummyneed <- subset(Adam, select = c("reptype", "pause", "search", "repeat", "cause"))

dummy_model <- dummyVars(" ~ .", data = dummyneed)

encoded_data <- predict(dummy_model, newdata = dummyneed)

encoded_data <- as.data.frame(encoded_data)

encoded_data[is.na(encoded_data)] <- 0
```

```{r}
colnames(encoded_data) <- sub("^[^.]+\\.", "", colnames(encoded_data))
colnames(encoded_data) <- sub("`repeat`", "", colnames(encoded_data))
```


```{r}
count_co_occurrence <- function(df) {
  combn(names(df), 2, simplify = FALSE) %>%
    map_dfr(~ {
      var1 <- .x[1]
      var2 <- .x[2]
      data.frame(
        pair = paste(var1, var2, sep = " & "),
        count = sum(df[[var1]] == 1 & df[[var2]] == 1)
      )
    })
}

# Apply the function to your data
co_occurrence_df <- count_co_occurrence(encoded_data)

co_occurrence_df <- co_occurrence_df %>% filter(count > 0)
```

```{r}
library(igraph)
library(RColorBrewer)
```

```{r}
co_occurrence_df <- co_occurrence_df %>%
  separate(pair, into = c("event1", "event2"), sep = " & ")
```

```{r}
edges <- as.data.frame(cbind(co_occurrence_df$event1, co_occurrence_df$event2))

g <- graph_from_data_frame(edges, directed = FALSE)

E(g)$weight <- co_occurrence_df$count

# Assign a unique color to each node
unique_events <- unique(c(co_occurrence_df$event1, co_occurrence_df$event2))  # Get unique event names (nodes)

pal <- colorRampPalette( brewer.pal(9,"Set3") )(21)
  
# Map each node to a unique color
vertex.col <- pal[match(V(g)$name, unique_events)]
```

```{r}
plot(g,
     #vertex.label.color = "black",
     #vertex.frame.color = "black",
     #edge.color = "black",
     vertex.color = vertex.col,
     vertex.label.cex = 0.7,
     layout = layout_in_circle,
     main = "Event Co-occurrence Graph")

# Add a legend
legend("topleft", bty = "n", 
       legend = unique_events, 
       fill = pal, border = NA, cex = 0.6)
```

