---
title: "group comparison"
author: "Samuel Vinter"
date: "2024-12-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pacman::p_load(tidyverse, dplyr, ggplot2, readr, car, lme4, pals, tidyr, caret, reshape2)
```

```{r}
setwd("../csv")
AD <- read_csv("proccsv/AD.csv")
AH <- read_csv("proccsv/AH.csv")
AS <- read_csv("proccsv/AS.csv")
Albert <- read_csv("proccsv/Albert.csv")
Anthony <- read_csv("proccsv/Anthony.csv")
Adam <- read_csv("proccsv/Adam.csv")

folder_path <- "fullcsv"
csv_files <- list.files(path = folder_path, pattern = "\\.csv$", full.names = TRUE)

for (file in csv_files) {
  file_name <- tools::file_path_sans_ext(basename(file))
  assign(file_name, read_delim(file, delim = ";"))
}
```

```{r}
# function to make descriptive stuff for each kid

counts <- function(group, chi, rep, full2, full4, full6){
  # its a little tricky cause adam is 1/3/5 but everyone else is 2/4/6
  n_full_utt_2 <- nrow(full2) # n of total utterances for 1/2
  n_full_utt_4 <- nrow(full4) # n of total utterances 3/4
  n_full_utt_6 <- nrow(full6) # n of total utterances 5/6
  
  n_chi_utt_2 <- full2 %>% # all of child utterances 1/2
    filter(Speaker=="CHI") %>%
    nrow()
  n_chi_utt_4 <- full4 %>% # all of child utterances 3/4
    filter(Speaker=="CHI") %>%
    nrow()
  n_chi_utt_6 <- full6 %>% # all of child utterances 5/6
    filter(Speaker=="CHI") %>%
    nrow()
  
  chi_2_rep <- rep %>% # n of repairs in 1/2
    filter(grepl("1|2", file)) %>%
    nrow()
  chi_4_rep <- rep %>% # n of repairs in 3/4
    filter(grepl("3|4", file)) %>%
    nrow()
  chi_6_rep <- rep %>%  # n of repairs 5/6
    filter(grepl("5|6", file)) %>%
    nrow()
  
  # how much does the kid speak relatively
  chi_vs_total_2 <- n_chi_utt_2 / n_full_utt_2 
  chi_vs_total_4 <- n_chi_utt_4 / n_full_utt_4
  chi_vs_total_6 <- n_chi_utt_6 / n_full_utt_6
  
  # how much of the childs utterances is repairs
  rep_vs_chi_2 <- chi_2_rep / n_chi_utt_2 
  rep_vs_chi_4 <- chi_4_rep / n_chi_utt_4
  rep_vs_chi_6 <- chi_6_rep / n_chi_utt_6
  
  # how much incomprehensible speech, marked xxx
  n_xxx_2 <- sum(stringr::str_count(full2$Utterance, "xxx")) 
  n_xxx_4 <- sum(stringr::str_count(full4$Utterance, "xxx"))
  n_xxx_6 <- sum(stringr::str_count(full6$Utterance, "xxx"))
  
  # how much incompr speech relative to utterances
  xxx_vs_chi_2 <- n_xxx_2 / n_chi_utt_2
  xxx_vs_chi_4 <- n_xxx_4 / n_chi_utt_4
  xxx_vs_chi_6 <- n_xxx_6 / n_chi_utt_6
  
  df <- tibble(
    group = c(group, group, group),
    chi = c(chi, chi, chi),
    session = c(2, 4, 6),
    total_utt = c(n_full_utt_2, n_full_utt_4, n_full_utt_6),
    total_chi_utt = c(n_chi_utt_2, n_chi_utt_4, n_chi_utt_6),
    chi_utt_vs_total_utt = c(chi_vs_total_2, chi_vs_total_4, chi_vs_total_6),
    n_of_repairs = c(chi_2_rep, chi_4_rep, chi_6_rep),
    repair_vs_chi_utt = c(rep_vs_chi_2, rep_vs_chi_4, rep_vs_chi_6),
    n_xxx = c(n_xxx_2, n_xxx_4, n_xxx_6),
    xxx_vs_chi = c(xxx_vs_chi_2, xxx_vs_chi_4, xxx_vs_chi_6)
    
  )
  
  return(df)
  
}
```

```{r}
Adam_count <- counts("long", "Adam", Adam, Adam_1, Adam_3, Adam_5)
Albert_count <- counts("long", "Albert", Albert, Albert_2, Albert_4, Albert_6)
Anthony_count <- counts("long", "Anthony", Anthony, Anthony_2, Anthony_4, Anthony_6)
AD_count <- counts("short", "AD", AD, AD_2, AD_4, AD_6)
AH_count <- counts("short", "AH", AH, AH_2, AH_4, AH_6)
AS_count <- counts("short", "AS", AS, AS2_2, AS2_4, AS2_6)
```


```{r}
group_all_count <- rbind(Adam_count, Albert_count, Anthony_count, AD_count, AH_count, AS_count)
group_all_count$session <- as.factor(group_all_count$session)
```

```{r}
# means and standard deviations between each group 
summary_count_grp <- group_all_count %>%
  group_by(group) %>%
  summarise(
    total_utt_mean = mean(total_utt, na.rm = TRUE),
    total_utt_sd = sd(total_utt, na.rm = TRUE),
    
    total_chi_utt_mean = mean(total_chi_utt, na.rm = TRUE),
    total_chi_utt_sd = sd(total_chi_utt, na.rm = TRUE),
    
    chi_utt_vs_total_utt_mean = mean(chi_utt_vs_total_utt, na.rm = TRUE),
    chi_utt_vs_total_utt_sd = sd(chi_utt_vs_total_utt, na.rm = TRUE),
    
    n_of_repairs_mean = mean(n_of_repairs, na.rm = TRUE),
    n_of_repairs_sd = sd(n_of_repairs, na.rm = TRUE),
    
    repair_vs_chi_utt_mean = mean(repair_vs_chi_utt, na.rm = TRUE),
    repair_vs_chi_utt_sd = sd(repair_vs_chi_utt, na.rm = TRUE),
    
    n_xxx_mean = mean(n_xxx, na.rm = TRUE),
    n_xxx_sd = sd(n_xxx, na.rm = TRUE),
    
    xxx_vs_chi_mean = mean(xxx_vs_chi, na.rm = TRUE),
    xxx_vs_chi_sd = sd(xxx_vs_chi, na.rm = TRUE)
  )

print(summary_count_grp)
```

```{r}
# summaries of means and sds for sessions and groups
summary_count_session_group <- group_all_count %>%
  group_by(group, session) %>%
  summarise(
    total_utt_mean = mean(total_utt, na.rm = TRUE),
    total_utt_sd = sd(total_utt, na.rm = TRUE),
    
    total_chi_utt_mean = mean(total_chi_utt, na.rm = TRUE),
    total_chi_utt_sd = sd(total_chi_utt, na.rm = TRUE),
    
    chi_utt_vs_total_utt_mean = mean(chi_utt_vs_total_utt, na.rm = TRUE),
    chi_utt_vs_total_utt_sd = sd(chi_utt_vs_total_utt, na.rm = TRUE),
    
    n_of_repairs_mean = mean(n_of_repairs, na.rm = TRUE),
    n_of_repairs_sd = sd(n_of_repairs, na.rm = TRUE),
    
    repair_vs_chi_utt_mean = mean(repair_vs_chi_utt, na.rm = TRUE),
    repair_vs_chi_utt_sd = sd(repair_vs_chi_utt, na.rm = TRUE),
    
    n_xxx_mean = mean(n_xxx, na.rm = TRUE),
    n_xxx_sd = sd(n_xxx, na.rm = TRUE),
    
    xxx_vs_chi_mean = mean(xxx_vs_chi, na.rm = TRUE),
    xxx_vs_chi_sd = sd(xxx_vs_chi, na.rm = TRUE)
  ) %>%
  arrange(session)

print(summary_count_session_group)
```

```{r}
# violin and boxplots for different things
ggplot(group_all_count, aes(x = session, y = total_chi_utt, fill = group)) +
  geom_violin(trim = FALSE) +
  labs(title = "Distribution of total child utterances by session and group", y = "total number of child utterances", x = "Session") +
  theme_minimal()

ggplot(group_all_count, aes(x = session, y = total_chi_utt, fill = group)) +
  geom_boxplot() +
  labs(title = "Distribution of total child utterances by session and group", y = "total number of child utterances", x = "Session") +
  theme_minimal()

ggplot(group_all_count, aes(x = session, y = chi_utt_vs_total_utt*100, fill = group)) +
  geom_violin(trim = FALSE) +
  labs(title = "Distribution of proportion of child utterances to total utt.-s by session and group", y = "proportion of child utterances in %", x = "Session") +
  theme_minimal()

ggplot(group_all_count, aes(x = session, y = chi_utt_vs_total_utt*100, fill = group)) +
  geom_boxplot() +
  labs(title = "Distribution of proportion of child utterances to total utt.-s by session and group", y = "proportion of child utterances in %", x = "Session") +
  theme_minimal()

ggplot(group_all_count, aes(x = session, y = n_of_repairs, fill = group)) +
  geom_violin(trim = FALSE) +
  labs(title = "Distribution of total repairs by session and group", y = "total number of repairs", x = "Session") +
  theme_minimal()

ggplot(group_all_count, aes(x = session, y = n_of_repairs, fill = group)) +
  geom_boxplot() +
  labs(title = "Distribution of total repairs by session and group", y = "total number of repairs", x = "Session") +
  theme_minimal()

ggplot(group_all_count, aes(x = session, y = repair_vs_chi_utt*100, fill = group)) +
  geom_violin(trim = FALSE) +
  labs(title = "Distribution of proportion of repairs to child utt.-s by session and group", y = "proportion of repairs in %", x = "Session") +
  theme_minimal()

ggplot(group_all_count, aes(x = session, y = repair_vs_chi_utt*100, fill = group)) +
  geom_boxplot() +
  labs(title = "Distribution of proportion of repairs to child utt.-s by session and group", y = "proportion of repairs in %", x = "Session") +
  theme_minimal()
```
############################################

███████ ████████  █████  ████████ ███████ 
██         ██    ██   ██    ██    ██      
███████    ██    ███████    ██    ███████ 
     ██    ██    ██   ██    ██         ██ 
███████    ██    ██   ██    ██    ███████ 
                                          
                                          
████████ ███████ ███████ ████████ ███████ 
   ██    ██      ██         ██    ██      
   ██    █████   ███████    ██    ███████ 
   ██    ██           ██    ██         ██ 
   ██    ███████ ███████    ██    ███████

############################################

```{r}
# t test for child utterances in proportion to total utterances, by group
shapiro.test(group_all_count$chi_utt_vs_total_utt)

hist(group_all_count$chi_utt_vs_total_utt)
qqnorm(group_all_count$chi_utt_vs_total_utt)
qqline(group_all_count$chi_utt_vs_total_utt, col = "red")

t.test(chi_utt_vs_total_utt ~ group, data = group_all_count) # significant!
```


```{r}
# wilcox test and transformed data t test for repairs in proportion to child utterances
hist(group_all_count$repair_vs_chi_utt)
qqnorm(group_all_count$repair_vs_chi_utt)
qqline(group_all_count$repair_vs_chi_utt, col = "red")

wilcox.test(repair_vs_chi_utt ~ group, data = group_all_count)

arcsine_repair = asin(sqrt(group_all_count$repair_vs_chi_utt))
hist(arcsine_repair)
qqnorm(arcsine_repair)
qqline(arcsine_repair, col = "red")

t.test(arcsine_repair ~ group, data = group_all_count) # not significant 
```


```{r}
# wilcox tests for abs counts of child utterances and repairs
hist(group_all_count$total_chi_utt)
hist(group_all_count$n_of_repairs)
wilcox.test(total_chi_utt ~ group, data = group_all_count)
wilcox.test(n_of_repairs ~ group, data = group_all_count) # once again, utterances are significant but repairs are not
```

```{r}
# anova for child utterance proportions, by group and session
anova_child_utt <- aov(chi_utt_vs_total_utt ~ group * session,
  data = group_all_count
)

plot(anova_child_utt, which=3)

leveneTest(anova_child_utt)

summary(anova_child_utt) # group has a significant effect but nothing else
```

```{r}
# anova for repairs in prop to chi utts, also by group and session
anova_rep <- aov(repair_vs_chi_utt ~ group * session, data = group_all_count)

plot(anova_rep, which=2)
plot(anova_rep, which=3)

leveneTest(anova_rep) 

summary(anova_rep) # group has a mildly significantŠ effect?
```

```{r}
m0 <- lm(repair_vs_chi_utt ~ group + chi_utt_vs_total_utt, data = group_all_count)
summary(m0)
```

```{r}
m1_utt <- lmer(chi_utt_vs_total_utt ~ group * session + (1 | chi), data = group_all_count)
m1_rep <- lmer(repair_vs_chi_utt ~ group * session + (1 | chi), data = group_all_count)
summary(m1_utt)
summary(m1_rep)
```
#############################################

██████  ███████ ██████   █████  ██ ██████  
██   ██ ██      ██   ██ ██   ██ ██ ██   ██ 
██████  █████   ██████  ███████ ██ ██████  
██   ██ ██      ██      ██   ██ ██ ██   ██ 
██   ██ ███████ ██      ██   ██ ██ ██   ██ 
                                           
                                           
████████ ██    ██ ██████  ███████ ███████  
   ██     ██  ██  ██   ██ ██      ██       
   ██      ████   ██████  █████   ███████  
   ██       ██    ██      ██           ██  
   ██       ██    ██      ███████ ███████ 
   
#############################################

```{r}
Adam <- Adam %>%
  mutate(row_number = row_number()) %>%
  mutate(session = case_when(
    grepl("1|2", file) ~ 2,
    grepl("3|4", file) ~ 4,
    grepl("5|6", file) ~ 6,
  ))

Albert <- Albert %>%
  mutate(row_number = row_number())%>%
  mutate(session = case_when(
    grepl("1|2", file) ~ 2,
    grepl("3|4", file) ~ 4,
    grepl("5|6", file) ~ 6,
  ))

Anthony <- Anthony %>%
  mutate(row_number = row_number())%>%
  mutate(session = case_when(
    grepl("1|2", file) ~ 2,
    grepl("3|4", file) ~ 4,
    grepl("5|6", file) ~ 6,
  ))

AD <- AD %>%
  mutate(row_number = row_number())%>%
  mutate(session = case_when(
    grepl("1|2", file) ~ 2,
    grepl("3|4", file) ~ 4,
    grepl("5|6", file) ~ 6,
  ))

AH <- AH %>%
  mutate(row_number = row_number())%>%
  mutate(session = case_when(
    grepl("1|2", file) ~ 2,
    grepl("3|4", file) ~ 4,
    grepl("5|6", file) ~ 6,
  ))

AS <- AS %>%
  mutate(row_number = row_number())%>%
  mutate(session = case_when(
    grepl("1|2", file) ~ 2,
    grepl("3|4", file) ~ 4,
    grepl("5|6", file) ~ 6,
  ))
```

```{r}
long_group <- rbind(Adam, Albert, Anthony) %>%
  mutate(group = "long")

short_group <- rbind(AD, AH, AS) %>%
  mutate(group = "short")

all <- rbind(long_group, short_group) %>%
    select(!other)

factorcols <- c("file", "Speaker", "type", "reptype", "pause", "search", "repeat", "cause", "session", "group")
all[factorcols] <- lapply(all[factorcols], factor)

all$reptype <- as.factor(all$reptype)
```

```{r}
colors_rep <- as.vector(trubetskoy(14))

names(colors_rep) <- levels(all$reptype)
colScale_reptype <- list(
  scale_fill_manual(name = "Repair type", values = colors_rep),
  scale_colour_manual(name = "Repair type", values = colors_rep)
)
```

```{r}
all_l <- all %>%
    pivot_longer(
      cols = c("pause", "search", "repeat", "cause"),
      names_to = "more",
      values_to = "whatsmore",
      values_drop_na = FALSE
    )

factorcols <- c("more", "whatsmore")
all_l[factorcols] <- lapply(all_l[factorcols], factor)

l_colors <- c(
  "short pause" = "firebrick",
  "long pause" = "salmon",
  "pause search" = "violet",
  "repetition search" = "purple",
  "small search" = "dodgerblue",
  "big search" = "mediumblue",
  "small repeat" = "green",
  "big repeat" = "darkgreen",
  "correcting grammar" = "darkkhaki",
  "misspeak" = "khaki",
  "overlap" = "orange",
  "stuttering" = "saddlebrown",
  "no uptake" = "#362110"
)

colScale_moretype <- list(
  scale_colour_manual(name = "Repair (sub)types, causes",values = l_colors),
  scale_fill_manual(name = "Repair (sub)types, causes",values = l_colors)
)
```

```{r}
long_group <- subset(all, group=="long")
short_group <- subset(all, group=="short")
```


```{r}
ggplot(long_group, aes(x = reorder(reptype, reptype, function(x)-length(x)))) +
  aes(fill = reptype) +
  geom_bar() +
  xlab("Repair type") +
  ggtitle("Repair types by count, long name group") +
  colScale_reptype+ 
  theme(axis.text.x = element_text(angle = 70, hjust=1))

ggplot(short_group, aes(x = reorder(reptype, reptype, function(x)-length(x)))) +
  aes(fill = reptype) +
  geom_bar() +
  xlab("Repair type") +
  ggtitle("Repair types by count, short name group")+
  colScale_reptype+ 
  theme(axis.text.x = element_text(angle = 70, hjust=1))
```

```{r}
long_reptype_summary <- long_group %>%
  group_by(session, reptype) %>%
  summarise(count = n(), .groups = "drop") %>%
  drop_na(reptype) %>%
  mutate(label = ifelse(count < 5, NA, count))
long_reptype_summary$reptype <- reorder(long_reptype_summary$reptype, long_reptype_summary$count, sum)

ggplot(long_reptype_summary, aes(x = session, y=count, fill=reptype, group=reptype)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = label), 
            position = position_stack(vjust = 0.5), 
            size = 2.5) +
  colScale_reptype+ 
  ggtitle("Repair types over time (total) for long name group") +
  theme_gray()

short_reptype_summary <- short_group %>%
  group_by(session, reptype) %>%
  summarise(count = n(), .groups = "drop") %>%
  drop_na(reptype) %>%
  mutate(label = ifelse(count < 5, NA, count)) 
short_reptype_summary$reptype <- reorder(short_reptype_summary$reptype, short_reptype_summary$count)

ggplot(short_reptype_summary, aes(x = session, y=count, fill=reptype, group=reptype)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = label), 
            position = position_stack(vjust = 0.5), 
            size = 2.5) +
  colScale_reptype+ 
  ggtitle("Repair types over time (total) for short name group") +
  theme_gray()
```

```{r}
long_utterances <- group_all_count %>%
  filter(group=="long") %>%
  group_by(session) %>%
  summarize(chi_utt = sum(total_chi_utt))

short_utterances <- group_all_count %>%
  filter(group=="short") %>%
  group_by(session) %>%
  summarize(chi_utt = sum(total_chi_utt))
```

```{r}
long_reptype_summary$session <- as.factor(long_reptype_summary$session)
long_reptype_props_utts <- long_reptype_summary %>%
  left_join(long_utterances, by="session") %>%
  mutate(proportion = count/chi_utt) %>%
  mutate(label = ifelse(proportion < 0.01, NA, proportion)) %>%
  mutate(label = round(label, 4))
long_reptype_props_utts$reptype <- reorder(long_reptype_props_utts$reptype, long_reptype_props_utts$proportion)

short_reptype_summary$session <- as.factor(short_reptype_summary$session)
short_reptype_props_utts <- short_reptype_summary %>%
  left_join(short_utterances, by="session") %>%
  mutate(proportion = count/chi_utt) %>%
  mutate(label = ifelse(proportion < 0.01, NA, proportion)) %>%
  mutate(label = round(label, 4))
short_reptype_props_utts$reptype <- reorder(short_reptype_props_utts$reptype, short_reptype_props_utts$proportion)
```

```{r}
ggplot(long_reptype_props_utts, aes(x = session, y = proportion*100, color = reptype, group = reptype)) +
  geom_line(size = 1, alpha = 0.7) +
  geom_point(size = 2) +
  geom_text(aes(label = scales::percent(proportion, accuracy = 0.01)), vjust = -0.6, size = 3) +
  labs(y = "proportion, %") +
  ggtitle("Repair types over time (relative to all chi utt) for long name group") +
  colScale_reptype

ggplot(long_reptype_props_utts, aes(x = session, y = proportion*100, fill = reptype, group = reptype)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = scales::percent(proportion, accuracy = 0.01)), 
            position = position_stack(vjust = 0.5), 
            size = 2.5) +
  labs(y = "proportion, %") +
  ggtitle("Repair types over time (relative to all chi utt) for long name group") +
  colScale_reptype




ggplot(short_reptype_props_utts, aes(x = session, y = proportion*100, color = reptype, group = reptype)) +
  geom_line(size = 1, alpha = 0.7) +
  geom_point(size = 2) +
  geom_text(aes(label = scales::percent(proportion, accuracy = 0.01)), vjust = -0.6, size = 3) +
  labs(y = "proportion, %") +
  ggtitle("Repair types over time (relative to all chi utt) for short name group") +
  colScale_reptype


ggplot(short_reptype_props_utts, aes(x = session, y = proportion*100, fill = reptype, group = reptype)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = scales::percent(proportion, accuracy = 0.01)), 
            position = position_stack(vjust = 0.5), 
            size = 2.5) +
  labs(y = "proportion, %") +
  ggtitle("Repair types over time (relative to all chi utt) for short name group") +
  colScale_reptype
```


```{r}
long_total_repairs <- long_group %>%
  group_by(session) %>%
  drop_na(reptype) %>%
  summarise(repair_count = n())

long_reptype_summary_props <- long_reptype_summary %>%
  left_join(long_total_repairs, by = "session") %>%
  mutate(proportion = count / repair_count) %>%
  mutate(label = ifelse(proportion < 0.01, NA, proportion)) %>%
  mutate(label = round(label, 4))

ggplot(long_reptype_summary_props, aes(x = session, y = proportion*100, color = reptype, group = reptype)) +
  geom_line(size = 1, alpha = 0.7) +
  geom_point(size = 2) +
  geom_text(aes(label = scales::percent(proportion, accuracy = 0.01)), vjust = -0.6, size = 3) +
  labs(y = "proportion, %") +
  ggtitle("Repair types proportions for long name group") +
  colScale_reptype

long_reptype_summary_props$reptype <- reorder(long_reptype_summary_props$reptype, long_reptype_summary_props$proportion)

ggplot(long_reptype_summary_props, aes(x = session, y = proportion*100, fill = reptype, group = reptype)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = scales::percent(proportion, accuracy = 0.01)), 
            position = position_stack(vjust = 0.5), 
            size = 2.5) +
  labs(y = "proportion, %") +
  ggtitle("Repair types proportions for long name group") +
  colScale_reptype



short_total_repairs <- short_group %>%
  group_by(session) %>%
  drop_na(reptype) %>%
  summarise(repair_count = n())

short_reptype_summary_props <- short_reptype_summary %>%
  left_join(short_total_repairs, by = "session") %>%
  mutate(proportion = count / repair_count) %>%
  mutate(label = ifelse(proportion < 0.01, NA, proportion)) %>%
  mutate(label = round(label, 4))


ggplot(short_reptype_summary_props, aes(x = session, y = proportion*100, color = reptype, group = reptype)) +
  geom_line(size = 1, alpha = 0.7) +
  geom_point(size = 2) +
  geom_text(aes(label = scales::percent(proportion, accuracy = 0.01)), vjust = -0.6, size = 3) +
  labs(y = "proportion, %") +
  ggtitle("Repair types proportions for short name group") +
  colScale_reptype

short_reptype_summary_props$reptype <- reorder(short_reptype_summary_props$reptype, short_reptype_summary_props$proportion)

ggplot(short_reptype_summary_props, aes(x = session, y = proportion*100, fill = reptype, group = reptype)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = scales::percent(proportion, accuracy = 0.01)), 
            position = position_stack(vjust = 0.5), 
            size = 2.5) +
  labs(y = "proportion, %") +
  ggtitle("Repair types proportions for short name group") +
  colScale_reptype
```


```{r}
long_l <- subset(all_l, group=="long") 
short_l <- subset(all_l, group=="short") 
```

```{r}
long_l_summary <- long_l %>%
  drop_na(whatsmore) %>%
  group_by(session, whatsmore) %>%
  summarise(count = n()) %>%
  mutate(label = ifelse(count < 5, NA, count))
long_l_summary$whatsmore <- reorder(long_l_summary$whatsmore, long_l_summary$count, sum)

ggplot(long_l_summary, aes(x = session, y=count, fill=whatsmore, group=whatsmore)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = label), 
            position = position_stack(vjust = 0.5), 
            size = 2.5) +
  ggtitle("Repair causes, types over time (total) for long name group") +
  colScale_moretype

short_l_summary <- short_l %>%
  drop_na(whatsmore) %>%
  group_by(session, whatsmore) %>%
  summarise(count = n(), .groups = "drop") %>%
  mutate(label = ifelse(count < 5, NA, count))
short_l_summary$whatsmore <- reorder(short_l_summary$whatsmore, short_l_summary$count, sum)

ggplot(short_l_summary, aes(x = session, y=count, fill=whatsmore, group=whatsmore)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = label), 
            position = position_stack(vjust = 0.5), 
            size = 2.5) +
  ggtitle("Repair causes, types over time (total) for short name group")+
  colScale_moretype
```

```{r}
# long_l_props_total <- long_l_summary %>%
#   left_join(long_total_repairs, by = "session") %>%
#   mutate(proportion = count / repair_count) %>%
#   mutate(label = ifelse(proportion < 0.004, NA, proportion)) %>%
#   mutate(label = round(label, 4))
# 
# short_l_props_total <- short_l_summary %>%
#   left_join(short_total_repairs, by = "session") %>%
#   mutate(proportion = count / repair_count) %>%
#   mutate(label = ifelse(proportion < 0.004, NA, proportion)) %>%
#   mutate(label = round(label, 4))
# 
# ggplot(long_l_props_total, aes(x = session, y = proportion*100, color = whatsmore, group = whatsmore)) +
#   geom_line(size = 1, alpha = 0.7) +
#   geom_point(size = 2) +
#   geom_text(aes(label = scales::percent(proportion, accuracy = 0.01)), vjust = -0.6, size = 3) +
#   labs(y = "proportion, %") +
#   ggtitle("Repair causes/types (relative to total repairs), long names")+
#   colScale_moretype
# 
# ggplot(short_l_props_total, aes(x = session, y = proportion*100, color = whatsmore, group = whatsmore)) +
#   geom_line(size = 1, alpha = 0.7) +
#   geom_point(size = 2) +
#   geom_text(aes(label = scales::percent(proportion, accuracy = 0.01)), vjust = -0.6, size = 3) +
#   labs(y = "proportion, %") +
#   ggtitle("Repair causes/types (relative to total repairs), short names")+
#   colScale_moretype
# 
# 
# long_l_props_total$whatsmore <- reorder(long_l_props_total$whatsmore, long_l_props_total$proportion, sum)
# 
# ggplot(long_l_props_total, aes(x = session, y = proportion*100, fill = whatsmore, group = whatsmore)) +
#   geom_bar(stat = "identity") +
#   geom_text(aes(label = scales::percent(proportion, accuracy = 0.01)), 
#             position = position_stack(vjust = 0.5), 
#             size = 2.5) +
#   labs(y = "proportion, %") +
#   ggtitle("Repair causes/types (relative to total repairs), long names")+
#   colScale_moretype
# 
# short_l_props_total$whatsmore <- reorder(short_l_props_total$whatsmore, short_l_props_total$proportion, sum)
# 
# ggplot(short_l_props_total, aes(x = session, y = proportion*100, fill = whatsmore, group = whatsmore)) +
#   geom_bar(stat = "identity") +
#   geom_text(aes(label = scales::percent(proportion, accuracy = 0.01)), 
#             position = position_stack(vjust = 0.5), 
#             size = 2.5) +
#   labs(y = "proportion, %") +
#   ggtitle("Repair causes/types (relative to total repairs), short names")+
#   colScale_moretype
```

```{r}
long_l_total_repairs <- long_l %>%
  drop_na(whatsmore) %>%
  group_by(session)  %>%
  summarise(repair_count = n())

short_l_total_repairs <- short_l %>%
  drop_na(whatsmore) %>%
  group_by(session) %>%
  summarise(repair_count = n())

long_l_props_melted <- long_l_summary %>% # out of all of the lines that have a whatsmore
  left_join(long_l_total_repairs, by = "session") %>%
  mutate(proportion = count / repair_count) %>%
  mutate(label = ifelse(proportion < 0.004, NA, proportion)) %>%
  mutate(label = round(label, 4))

short_l_props_melted <- short_l_summary %>%
  left_join(short_l_total_repairs, by = "session") %>%
  mutate(proportion = count / repair_count) %>%
  mutate(label = ifelse(proportion < 0.004, NA, proportion)) %>%
  mutate(label = round(label, 4))

ggplot(long_l_props_melted, aes(x = session, y = proportion*100, color = whatsmore, group = whatsmore)) +
  geom_line(size = 1, alpha = 0.7) +
  geom_point(size = 2) +
  geom_text(aes(label = scales::percent(proportion, accuracy = 0.01)), vjust = -0.6, size = 3) +
  labs(y = "proportion, %") +
  ggtitle("Repair causes/subtypes proportions, long names")+
  colScale_moretype

ggplot(short_l_props_melted, aes(x = session, y = proportion*100, color = whatsmore, group = whatsmore)) +
  geom_line(size = 1, alpha = 0.7) +
  geom_point(size = 2) +
  geom_text(aes(label = scales::percent(proportion, accuracy = 0.01)), vjust = -0.6, size = 3) +
  labs(y = "proportion, %") +
  ggtitle("Repair causes/subtypes proportions, short names")+
  colScale_moretype


long_l_props_melted$whatsmore <- reorder(long_l_props_melted$whatsmore, long_l_props_melted$proportion, sum)

ggplot(long_l_props_melted, aes(x = session, y = proportion*100, fill = whatsmore, group = whatsmore)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = scales::percent(proportion, accuracy = 0.01)), 
            position = position_stack(vjust = 0.5), 
            size = 2.5) +
  labs(y = "proportion, %") +
  ggtitle("Repair causes/subtypes proportions, long names")+
  colScale_moretype

short_l_props_melted$whatsmore <- reorder(short_l_props_melted$whatsmore, short_l_props_melted$proportion, sum)

ggplot(short_l_props_melted, aes(x = session, y = proportion*100, fill = whatsmore, group = whatsmore)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = scales::percent(proportion, accuracy = 0.01)), 
            position = position_stack(vjust = 0.5), 
            size = 2.5) +
  labs(y = "proportion, %") +
  ggtitle("Repair causes/subtypes proportions, short names")+
  colScale_moretype
```


```{r}
nopause_long_total_repairs <- long_l %>%
  drop_na(whatsmore) %>%
  filter(!(whatsmore %in% "short pause")) %>%
  group_by(session) %>%
  summarise(repair_count = n())
```

```{r}
long_nopause_props <- long_l_summary %>%
  filter(!(whatsmore %in% "short pause")) %>%
  left_join(nopause_long_total_repairs, by = "session") %>%
  mutate(proportion = count / repair_count) %>%
  mutate(label_rel = ifelse(proportion < 0.004, NA, proportion)) %>%
  mutate(label_rel = round(label_rel, 4))

ggplot(long_nopause_props, aes(x = session, y = proportion*100, color = whatsmore, group = whatsmore)) +
  geom_line(size = 1, alpha = 0.7) +
  geom_point(size = 2) +
  geom_text(aes(label = scales::percent(proportion, accuracy = 0.01)), vjust = -0.5, size = 2.5) +
  labs(y = "proportion, %") +
  ggtitle("Repair causes, types over time (relative) for long name group, no short pauses")+
  colScale_moretype

long_nopause_props$whatsmore <- reorder(long_nopause_props$whatsmore, long_nopause_props$proportion, sum)

ggplot(long_nopause_props, aes(x = session, y = proportion*100, fill = whatsmore, group = whatsmore)) +
  geom_bar(stat = "identity") +
    geom_text(aes(label = scales::percent(proportion, accuracy = 0.01)), 
            position = position_stack(vjust = 0.5), 
            size = 2.5) +
  labs(y = "proportion, %") +
  ggtitle("Repair causes, types over time (relative) for long name group, no short pauses")+
  colScale_moretype
```

###################################################
████████ ██    ██ ██████  ███    ██ ███████ 
   ██    ██    ██ ██   ██ ████   ██ ██      
   ██    ██    ██ ██████  ██ ██  ██ ███████ 
   ██    ██    ██ ██   ██ ██  ██ ██      ██ 
   ██     ██████  ██   ██ ██   ████ ███████ 
                                            
###################################################

```{r}
long_turns <- long_group %>%
  group_by(session, type) %>%
  summarise(count = n(), .groups = "drop") %>%
  na.omit() %>%
  mutate(label = ifelse(count < 5, NA, count))
long_turns$type <- reorder(long_turns$type, long_turns$count, sum)

ggplot(long_turns, aes(x = session, y=count, fill=type, group=type)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = label), 
            position = position_stack(vjust = 0.5), 
            size = 3) +
  ggtitle("Turn types for repair over time (total) for long name group")

short_turns <- short_group %>%
  group_by(session, type) %>%
  summarise(count = n(), .groups = "drop") %>%
  na.omit() %>%
  mutate(label = ifelse(count < 5, NA, count))
short_turns$type <- reorder(short_turns$type, short_turns$count, sum)

ggplot(short_turns, aes(x = session, y=count, fill=type, group=type)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = label), 
            position = position_stack(vjust = 0.5), 
            size = 3) +
  ggtitle("Turn types for repair over time (total) for short name group")
```

```{r}
# should be total repairs not total utterances!
long_turns_rel <- long_turns %>%
  left_join(long_total_repairs, by = "session") %>%
  mutate(proportion = count / repair_count) %>%
  mutate(label = ifelse(proportion < 0.004, NA, proportion)) %>%
  mutate(label = round(label, 4))
long_turns_rel$type <- reorder(long_turns_rel$type, long_turns_rel$proportion)

short_turns_rel <- short_turns %>%
  left_join(short_total_repairs, by = "session") %>%
  mutate(proportion = count / repair_count) %>%
  mutate(label = ifelse(proportion < 0.004, NA, proportion)) %>%
  mutate(label = round(label, 4))
short_turns_rel$type <- reorder(short_turns_rel$type, short_turns_rel$proportion)
```

```{r}
ggplot(long_turns_rel, aes(x = session, y = proportion*100, color = type, group = type)) +
    geom_line(size = 1, alpha = 0.7) +
  geom_point(size = 2) +
  geom_text(aes(label = scales::percent(proportion, accuracy = 0.01)), vjust = -0.5, size = 2.5) +
  labs(y = "proportion, %") +
  ggtitle("Turn types (relative) for long name group")

ggplot(short_turns_rel, aes(x = session, y = proportion*100, color = type, group = type)) +
    geom_line(size = 1, alpha = 0.7) +
  geom_point(size = 2) +
  geom_text(aes(label = scales::percent(proportion, accuracy = 0.01)), vjust = -0.5, size = 2.5) +
  labs(y = "proportion, %") +
  ggtitle("Turn types (relative) for short name group")

ggplot(long_turns_rel, aes(x = session, y = proportion*100, fill = type, group = type)) +
  geom_bar(stat = "identity") +
    geom_text(aes(label = scales::percent(proportion, accuracy = 0.01)), 
            position = position_stack(vjust = 0.5), 
            size = 2.5) +
  labs(y = "proportion, %") +
  ggtitle("Turn types (relative) for long name group")


ggplot(short_turns_rel, aes(x = session, y = proportion*100, fill = type, group = type)) +
  geom_bar(stat = "identity") +
    geom_text(aes(label = scales::percent(proportion, accuracy = 0.01)), 
            position = position_stack(vjust = 0.5), 
            size = 2.5) +
  labs(y = "proportion, %") +
  ggtitle("Turn types (relative) for short name group")
```

#################################################################################

 ██████  ██████       ██████   ██████  ██████ ██    ██ ██████        ███████ 
██      ██    ██     ██    ██ ██      ██      ██    ██ ██   ██       ██      
██      ██    ██     ██    ██ ██      ██      ██    ██ ██████  █████ ███████ 
██      ██    ██     ██    ██ ██      ██      ██    ██ ██   ██            ██ 
 ██████  ██████       ██████   ██████  ██████  ██████  ██   ██       ███████ 

#################################################################################

```{r}
dummylong <- subset(long_group, select = c("reptype", "pause", "search", "repeat", "cause"))
dummy_model_long <- dummyVars(" ~ .", data = dummylong)
encoded_long <- predict(dummy_model_long, newdata = dummylong)
encoded_long <- as.data.frame(encoded_long)
encoded_long[is.na(encoded_long)] <- 0

colnames(encoded_long) <- sub("^[^.]+\\.", "", colnames(encoded_long))
colnames(encoded_long) <- sub("`repeat`", "", colnames(encoded_long))

coocc_long <- combn(names(encoded_long), 2, simplify = FALSE) %>%
    map_dfr(~ {
      var1 <- .x[1]
      var2 <- .x[2]
      data.frame(
        pair = paste(var1, var2, sep = " & "),
        count = sum(encoded_long[[var1]] == 1 & encoded_long[[var2]] == 1)
      )
    })

coocc_long <- coocc_long %>% 
  filter(count > 0)

coocc_long_sep <- coocc_long %>%
  separate(pair, into = c("event1", "event2"), sep = " & ")
```

```{r}
dummyshort <- subset(short_group, select = c("reptype", "pause", "search", "repeat", "cause"))
dummy_model_short <- dummyVars(" ~ .", data = dummyshort)
encoded_short <- predict(dummy_model_short, newdata = dummyshort)
encoded_short <- as.data.frame(encoded_short)
encoded_short[is.na(encoded_short)] <- 0

colnames(encoded_short) <- sub("^[^.]+\\.", "", colnames(encoded_short))
colnames(encoded_short) <- sub("`repeat`", "", colnames(encoded_short))

coocc_short <- combn(names(encoded_short), 2, simplify = FALSE) %>%
    map_dfr(~ {
      var1 <- .x[1]
      var2 <- .x[2]
      data.frame(
        pair = paste(var1, var2, sep = " & "),
        count = sum(encoded_short[[var1]] == 1 & encoded_short[[var2]] == 1)
      )
    })

coocc_short <- coocc_short %>% 
  filter(count > 0)

coocc_short_sep <- coocc_short %>%
  separate(pair, into = c("event1", "event2"), sep = " & ")
```

```{r}
comparison_df <- full_join(
  coocc_long, 
  coocc_short, 
  by = "pair", 
  suffix = c("_long", "_short")
)
```

```{r}
comparison_df <- comparison_df %>%
  mutate(
    count_long = replace_na(count_long, 0),
    count_short = replace_na(count_short, 0)
  )
```

```{r}
difference_df <- comparison_df %>%
  mutate(
    difference = count_long - count_short,
    abs_difference = abs(difference)
  ) %>%
  arrange(desc(abs_difference))

bubble_plot <- difference_df %>%
  mutate(
    direction = ifelse(difference > 0, "long", "short"),
    abs_difference = abs(difference)
  ) %>%
  ggplot(aes(x = reorder(pair, abs_difference), y = abs_difference, 
             size = abs_difference, color = direction)) +
  geom_point(alpha = 0.7) +
  coord_flip() +
  scale_color_manual(values = c("long" = "blue", "short" = "red")) +
  theme_minimal() +
  labs(
    title = "Co-occurrence Difference Magnitude",
    x = "Co-occurrence Pairs",
    y = "Absolute Difference in Occurrence",
    size = "Difference Magnitude",
    color = "Predominant Group"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

lollipop_plot <- difference_df %>%
  mutate(
    direction = ifelse(difference > 0, "long", "short"),
    abs_difference = abs(difference)
  ) %>%
  ggplot(aes(x = reorder(pair, abs_difference), y = difference, color = direction)) +
  geom_segment(aes(x = pair, xend = pair, y = 0, yend = difference)) +
  geom_point() +
  coord_flip() +
  scale_color_manual(values = c("long" = "blue", "short" = "red")) +
  theme_minimal() +
  labs(
    title = "Co-occurrence Difference",
    x = "Co-occurrence Pairs",
    y = "Difference in Occurrence (long-short)",
    color = "Predominant Group"
  )

bubble_plot
lollipop_plot
```


```{r}
coocc_long_matrix <- acast(coocc_long_sep, event1 ~ event2, value.var = "count", fill = 0)

coocc_short_matrix <- acast(coocc_short_sep, event1 ~ event2, value.var = "count", fun.aggregate = sum, fill = 0)
```


```{r}
ggplot(melt(coocc_long_matrix), aes(x = Var1, y = Var2, fill = value)) +
  geom_tile(color = "lightblue") +
  scale_fill_gradientn(colours = c("white", "yellow", "purple"), values = c(0,0.1,1))+
  geom_text(aes(label = value), color = "black", size = 3) +
  labs(x = "Event 1", y = "Event 2", fill = "Co-occurrences") +
  ggtitle("Co-occurrence matrix for long group") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(melt(coocc_short_matrix), aes(x = Var1, y = Var2, fill = value)) +
  geom_tile(color = "lightblue") +
  scale_fill_gradientn(colours = c("white", "yellow", "purple"), values = c(0,0.1,1))+
  geom_text(aes(label = value), color = "black", size = 3) +
  labs(x = "Event 1", y = "Event 2", fill = "Co-occurrences") +
  ggtitle("Co-occurrence matrix for short group") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
comparison_df_sep <- comparison_df %>%
  separate(pair, into = c("event1", "event2"), sep = " & ")
```

```{r}

```

